Repository meilisearch/documentation, pull requests merged in 2021-09, with the labels that each got.

#1097 v0.22: Sentry
  learn/what_is_meilisearch/telemetry.md
  resources/faq.md
Labels: next-release, waiting for review

#1087 v0.22: Sort
  .code-samples.meilisearch.yaml
  .vuepress/config.js
  .vuepress/public/sample-template.yaml
  errors.yaml
  learn/core_concepts/relevancy.md
  learn/what_is_meilisearch/features.md
  reference/api/ranking_rules.md
  reference/api/settings.md
  reference/api/sortable_attributes.md
  reference/features/search_parameters.md
  reference/features/settings.md
  reference/features/sorting.md
Labels: next-release, ready to be merged

#1106 Update Measured disk usage
  reference/under_the_hood/storage.md
Labels: next-release, ready to be merged

#1103 v0.22: Indexer
  reference/under_the_hood/indexation.md
  resources/faq.md
Labels: next-release, ready to be merged, waiting for review
