Repository meilisearch/documentation, pull requests merged in 2021-08, with the labels that each got.

#1046 v0.21: Update asynchronous update page
  learn/advanced/asynchronous_updates.md
  reference/features/search_parameters.md
Labels: next-release

#1048 v0.21: reset settings with `null`
  reference/api/settings.md
Labels: ready to be merged

#1047 Add warning for matches
  reference/features/search_parameters.md
Labels: ready to be merged

#1041 v0.21: Facets and filters
  .vuepress/config.js
  .vuepress/public/_redirects
  learn/what_is_meilisearch/features.md
  learn/what_is_meilisearch/philosophy.md
  reference/api/attributes_for_faceting.md
  reference/api/filterable_attributes.md
  reference/api/search.md
  reference/api/settings.md
  reference/features/README.md
  reference/features/faceted_search.md
  reference/features/filtering.md
  reference/features/filtering_and_faceted_search.md
  reference/features/search_parameters.md
  reference/features/settings.md
  reference/under_the_hood/datatypes.md
  resources/faq.md
Labels: next-release, ready to be merged
