Repository meilisearch/documentation, pull requests merged in 2021-11, with the labels that each got.

#1238 V0.24: attributesToHighlight
  reference/features/search_parameters.md
Labels: ready to be merged

#1220 v0.24 telemetry
  learn/what_is_meilisearch/telemetry.md
  reference/features/configuration.md
  resources/faq.md
Labels: ready to be merged

#1206 V0.24 increase limit number of positions per attribute
  learn/core_concepts/documents.md
  reference/features/known_limitations.md
Labels: ready to be merged

#1227 v0.24-update errors
  errors.yaml
  learn/advanced/asynchronous_updates.md
  reference/api/README.md
  reference/features/geosearch.md
  resources/faq.md
Labels: ready to be merged

#1276 v0.24: Update Asynchronous Updates guide code sample
  learn/advanced/asynchronous_updates.md
Labels: new release

#1291 add settings_guide_sortable_1 to code-samples and template
  .code-samples.meilisearch.yaml
  .vuepress/public/sample-template.yaml
Labels: code sample
