Repository meilisearch/documentation, pull requests merged in 2021-01, with the labels that each got.

#663 Remove Typesense from comparison
  resources/comparison_to_alternatives.md
Labels: enhancement, 🚨 URGENT 🚨

#659 Updating the default max payload size from 10mb to 100mb
  guides/advanced_guides/configuration.md
  guides/advanced_guides/known_limitations.md
  guides/main_concepts/documents.md
Labels: enhancement

#673 Prepare meilisearch 2021-w1
  .vuepress/config.js
  guides/advanced_guides/configuration.md
  guides/advanced_guides/known_limitations.md
  guides/advanced_guides/tokenization.md
  guides/main_concepts/documents.md
  index.md
Labels: next-release

#679 Field prop code sample
  .code-samples.meilisearch.yaml
  guides/advanced_guides/field_properties.md
Labels: content

#553 Add integration to quick start
  .vuepress/config.js
  guides/introduction/quick_start_guide.md
  package.json
  yarn.lock
Labels: enhancement

#722 fix Homebrew name
  guides/advanced_guides/installation.md
  guides/introduction/quick_start_guide.md
  resources/tutorials/running_production.md
Labels: content
